### PR TITLE
SVG1.1 Compliance for dots 

### PR DESCRIPTION
**Pull request by jacekd**
Based on the issue #10, I've added the missing props so they can be rendered in Firefox and Edge.

### CODE REVIEW

**Comment by Spyna** [comment]
Thank for the PR, 
please run a `npm run prettier` or `yarn prettier` to format the source code, in order to make it clearer for me to compare changes.

**Comment by jacekd** [comment]
done

**Comment by jacekd** [comment]
now prettier with single quote to match

**Comment by jacekd** [comment]
any movement on that?

**Pull request merged**
